### PR TITLE
add city test cases

### PR DESCRIPTION
**Pull request by tonydfth**

### CODE REVIEW

**Review by uroy007 — APPROVED** [review]
The code looked good.

But after testing found issue:

(1) tested with city = Urbana,
Savoy
failed as multiple records exist in database, please fix this issue.
(2) In comment where ever Chicago is there add a comment that "replace this with the city you need to test" as in the first place.
(3) Do we need .idea/androidTestResultsUserPreferences file ? I saw that it was generated after test.

**Review by uroy007 — CHANGES_REQUESTED** [review]
Has issue, 
(1) tested with city = Urbana, 
                                 Savoy 
failed as multiple records exist in database, please fix this issue.
(2) In comment where ever Chicago is there add a comment that "replace this with the city you need to test" as in the first place.
(3) Do we need .idea/androidTestResultsUserPreferences file ? I saw that it was generated after test.

**Comment by 883km** [comment]
When enter city name in the test, make sure to use "Cityname, State" format to avoid dups.

**Comment by uroy007** [comment]
that did not work, either the documentation should be corrected with proper explanation or code.

**Comment by tonydfth** [comment]
> Has issue, (1) tested with city = Urbana, Savoy failed as multiple records exist in database, please fix this issue. (2) In comment where ever Chicago is there add a comment that "replace this with the city you need to test" as in the first place. (3) Do we need .idea/androidTestResultsUserPreferences file ? I saw that it was generated after test.

Yes it is not meant to work with multiple cities. Why is this needed? The test case of adding Chicago should fulfill all the requirements

**Comment by tonydfth** [comment]
> When enter city name in the test, make sure to use "Cityname, State" format to avoid dups.

The format for add city input is only suppose to be the city name, state should not be included

**Review by uroy007 — APPROVED** [review]

**Pull request merged**
